version: "3.8"

services:
  db:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "WHATS_APP"
      MONGO_INITDB_ROOT_USERNAME: ""
      MONGO_INITDB_ROOT_PASSWORD: ""
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
