version: "3.8"

services:
  wp:
    image: wordpress:5.6
    container_name: wordpress
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: host
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
    volumes:
      - ./app:/var/www/html
    ports:
      - 8082:80
