version: "3.8"

services:
  db:
    image: mariadb:10.5.9
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
