version: "3.9"

services:
  web:
    image: nginx:1.23
    container_name: nginx
    volumes:
      - ./html:/var/www/html
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  php-fpm:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
