services:
  db:
    image: redis:7.4
    container_name: redis
    restart: always
    env_file: .env
    entrypoint: redis-server --appendonly yes  --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
